spring.application.name=rout24

jwt.secret=broryvpqpvqrbvpqjewcpiqbrvirqibhwbrvhbqrphbqpwirhbvrbwpihwqbrvbpiwrbv1
jwt.expiration-ms=3600000

spring.datasource.url=jdbc:postgresql://localhost:5432/rout24
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.defaultModelsExpandDepth=1
springdoc.swagger-ui.docExpansion=none

cloud.api.key=c74230e7a5cb9f3c0620d4c19ad29b13
